language: python
python:
- 2.7
install:
- pip install coveralls scrutinizer-ocular
script: make ci
after_script:
- coveralls
- ocular
notifications:
  email:
    on_success: never
    on_failure: always
