language: python
python:
- 3.6
install:
- pip install coveralls scrutinizer-ocular
script: make ci
after_success:
- coveralls
- ocular
notifications:
  email:
    on_success: never
    on_failure: always
