# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugee_manager', '0004_casefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynote',
            name='minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time spent in minutes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='access_to_services',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- No access to service or health care'), (2, '2- Minimal access to emergency services (E.R.)'), (3, '3- Minimal access to services beyond E.R.'), (4, '4- Has access to some minimal health care'), (5, '5- Has access to basic health care, one or two area services with assistance'), (6, '6- Has access to basic services without help, able to get to appointments'), (7, '7- Has access to services that will progress family with assistance'), (8, '8- Has access to services that will progress family without assistance'), (9, '9- Able to research and access services on own to support family and meet most needs'), (10, '10- Has skills to access and research services and health care independently')], default=0, null=True, verbose_name='Access to services and health care (family)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='access_to_services_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='education_or_training',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- No school or education in home country or here, no job training'), (2, '2- Primary school education, no job training'), (3, '3- Middle school education, no job training'), (4, '4- High school or above equivalent education, no job training'), (5, '5- Some schooling, basic job training skills'), (6, '6- Some schooling, multiple job trainings or skills'), (7, '7- Some schooling, advanced job training or skills'), (8, '8- Advanced job training or some college'), (9, '9- Advanced professional training or college degree'), (10, '10- Advanced professional training or advanced college degree')], default=0, null=True, verbose_name='School/ Education/ Job Training (parents)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='education_or_training_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='employment',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- Has no current job or past experience, does not want work'), (2, '2- Desires employment but has no current or past work experience'), (3, '3- Desires employment but has no current job, has some past experience'), (4, '4- Desires employment, has past experience and is actively seeking'), (5, '5- Has part time employment, low paying low skill position'), (6, '6- Has part time position, skilled position'), (7, '7- Has full time employment, low paying low skill position'), (8, '8- Has full time employment in skilled position but desires another position'), (9, '9- Has full time skilled position, is happy with pay and position'), (10, '10- Has full time professional or highly skilled position, is fulfilled with work')], default=0, null=True, verbose_name='Employment (wage earning parent)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='employment_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='finances',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- Has no employment income or DHS assistance'), (2, '2- Has no employment, some DHS assistance but insufficient for rent'), (3, '3- Has no employment, some DHS assistance but insufficient for needs'), (4, '4- Has minimal employment and/ or DHS but unable to meet basic needs'), (5, '5- Has minimal employment and/ or DHS, able to meet basic needs only'), (6, '6- Has employment and/ or DHS, able to meet needs and has minimal extra money'), (7, '7- Has employment and able to meet basic needs WITHOUT DHS assistance'), (8, '8- Has employment and able to meet more than basic needs WITHOUT DHS assistance'), (9, '9- Has employment, able to go above basic needs without assistance'), (10, '10- Has employment and financially stable')], default=0, null=True, verbose_name='Finances (family)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='finances_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='housing',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- Homeless'), (2, '2- Has temporary housing'), (3, '3- Has somewhat stable housing- month to month/ long term temporary, etc.'), (4, '4- Has apartment but inadequate for family needs and size'), (5, "5- Has stable apartment that is adequate, but family doesn't like area or cost"), (6, '6- Has stable apartment, good area and cost'), (7, '7- Has stable apartment, looking to move to better area or purchase home'), (8, '8- In process of purchasing home'), (9, '9- In own home, difficulties with size or mortgage'), (10, '10- In own home, appropriate size and monthly mortgage')], default=0, null=True, verbose_name='Housing (family)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='housing_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='language_skills',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1 - No English'), (2, '2 - Few phrases such as yes and thank you'), (3, '3 - Can answer a few questions'), (4, '4 - Able to have some basic skills- knows some nouns and verbs'), (5, '5 - Able to have basic conversation in some concrete areas'), (6, '6 - Able to have more than basic conversation- knows various tenses, etc.'), (7, '7 - Able to have in depth conversations around daily events'), (8, '8 - Able to have discussions around abstract concepts'), (9, '9 - Fluent other than some technical terms'), (10, '10 - Fluent, including in specialty areas')], default=0, verbose_name='Language Skills (highest level adult)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='language_skills_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mental_health',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- Many family members have serious mental health difficulties, many need occasional hospitalization, not receiving needed mental health care'), (2, '2- Many family members have serious mental health difficulties, many need occasional hospitalization, not receiving needed mental health care'), (3, '3- One family member has serious mental health difficulties, and others may have minor difficulties, not receiving needed mental health care'), (4, '4- One family member has serious mental health difficulties, and others may have minor difficulties, is receiving services needed'), (5, '5- One family member has serious mental health difficulties, and others may have minor difficulties, is receiving services needed'), (6, '6- One family member has serious mental health difficulties but is receiving interventions'), (7, '7- One family member has moderate mental health difficulties but is receiving interventions'), (8, '8- One family member has mild mental health difficulties but is receiving interventions'), (9, '9- Family members appear to be in good mental health but may occasionally have stress or acculturation difficulties'), (10, '10- Family members all appear to be in excellent mental health')], default=0, null=True, verbose_name='Mental Health (all family members)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mental_health_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='social_support',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- Has no social support, friends, etc.'), (2, '2- Only has social support from one agency or program'), (3, '3- Has social support from family members in household'), (4, '4- Only has social support from various agencies and/ or multiple household members'), (5, '5- Has support from one family member outside of the home or one friend'), (6, '6- Has support from more than one friend or outside family members'), (7, '7- Has support from multiple friends or family, participates in at least one social activity (church, support group, sewing club)'), (8, '8- Has support from multiple friends and family, actively involved in multiple settings'), (9, '9- Actively involved in the community'), (10, '10- Actively involved in the community and leads some activities')], default=0, null=True, verbose_name='Social Support (family)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='social_support_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='support_of_children',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- In need of parenting training, CPS involved, children may be in danger'), (2, '2- In need of parenting training, CPS involved, children appear safe'), (3, '3- In need of parenting skills, CPS may be involved, but parents want to support children'), (4, '4- In need of parenting skills or training to understand American schools, no CPS involvement, parents attempt to support children'), (5, '5- Some understanding of American school, parents need additional support, parents attempt to support children'), (6, '6- Parents need support, but have some ability to support children, attend conferences, can help with homework and understand school systems'), (7, '7- Parents able to support children in school with a minimum of support, can provide emotional support, help with homework, etc.'), (8, '8- Parents able to support children in school, provide recreational activities and emotional support'), (9, '9- Parents able to support children in most areas with minimal support from others'), (10, '10- Parents able to fully support children at home and in school')], default=0, null=True, verbose_name='Support of Children (parents)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='support_of_children_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='transportation',
            field=models.IntegerField(choices=[(0, '0 - Please Select'), (1, '1- No transportation, no knowledge of bus line'), (2, '2- No transportation, has been introduced to bus line but unwilling or unable to use'), (3, '3- Minimal transportation, able to use bus line to few selected locations'), (4, '4- Low level transportation, able to use bus line to some locations, has friends to transport at times, able to get to most appointments alone'), (5, '5- Able to use bus proficiently, able to get to appointments/work, has transportation network'), (6, '6- Able to network to get to appointments/work as needed, no driving experience'), (7, '7- Able to get to appointments/work, desires to learn how to drive and has some experience'), (8, '8- Some driving experience, working towards license'), (9, '9- Has license but no car'), (10, '10- Has license and car, able to transport self and family independently')], default=0, null=True, verbose_name='Transportation (family)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='transportation_note',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='case',
            name='other1',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='case',
            name='other2',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='case',
            name='other3',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='case',
            name='other4',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='case',
            name='other5',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ssn',
            field=models.CharField(blank=True, max_length=2000, verbose_name='SSN'),
        ),
    ]
