# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import employment_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refugee_manager', '0005_auto_20171103_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(max_length=10000)),
                ('minutes', models.IntegerField(blank=True, null=True, verbose_name='Time spent in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('TakenDate', models.DateField(verbose_name='Taken')),
                ('Score', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='EmploymentClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=80, verbose_name='Last Name')),
                ('StreetAddress', models.CharField(max_length=50, verbose_name='Address')),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=2)),
                ('Zip', models.CharField(max_length=10)),
                ('Phones', models.CharField(blank=True, max_length=50)),
                ('Active', models.BooleanField(default=True)),
                ('Other', models.TextField(blank=True)),
                ('volunteers', models.ManyToManyField(to='refugee_manager.Volunteer')),
            ],
            options={
                'verbose_name': 'Employment Client',
                'verbose_name_plural': 'Employment Clients',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50, verbose_name='Company')),
                ('Title', models.CharField(max_length=80, verbose_name='Title')),
                ('Description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(verbose_name='End Date')),
                ('employment_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_manager.EmploymentClient')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='Language')),
                ('Scale', employment_manager.models.IntegerRangeField(verbose_name='ILR Scale')),
                ('employment_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_manager.EmploymentClient')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200, verbose_name='Description')),
                ('employment_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_manager.EmploymentClient')),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='employment_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_manager.EmploymentClient'),
        ),
        migrations.AddField(
            model_name='activitynote',
            name='employment_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='employment_manager.EmploymentClient'),
        ),
        migrations.AddField(
            model_name='activitynote',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_activity', to='refugee_manager.Volunteer'),
        ),
    ]
