# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_date', models.DateField(verbose_name='Taken')),
                ('Score', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='Attended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateField(verbose_name='Attended')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
            },
        ),
        migrations.CreateModel(
            name='ESLStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=80, verbose_name='Last Name')),
                ('StreetAddress', models.CharField(max_length=50, verbose_name='Address')),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=2)),
                ('Zip', models.CharField(max_length=10)),
                ('Phones', models.CharField(blank=True, max_length=50)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ESL Student',
                'verbose_name_plural': 'ESL Students',
            },
        ),
        migrations.AddField(
            model_name='attended',
            name='esl_tudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esl_manager.ESLStudent'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='esl_tudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esl_manager.ESLStudent'),
        ),
    ]
